/**
 * %% Copyright (C) 2021 DataScience 9 LLC %% Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a
 * copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License. #L%
 *
 * <p>This code is 100% AUTO generated. Please do not modify it DIRECTLY If you need new features or
 * function or changes please update the templates then submit the template through our web
 * interface.
 */
package com.magento.test.dao;

import java.util.List;
import java.util.logging.Logger;

import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.inject.Named;

import com.magento.test.entity.AdminPasswords;
import com.magento.test.entity.AdminSystemMessages;
import com.magento.test.entity.AdminUser;
import com.magento.test.entity.AdminUserSession;
import com.magento.test.entity.AdminnotificationInbox;
import com.magento.test.entity.AmazonCustomer;
import com.magento.test.entity.AmazonPendingAuthorization;
import com.magento.test.entity.AmazonPendingCapture;
import com.magento.test.entity.AmazonPendingRefund;
import com.magento.test.entity.AmazonQuote;
import com.magento.test.entity.AmazonSalesOrder;
import com.magento.test.entity.AuthorizationRole;
import com.magento.test.entity.AuthorizationRule;
import com.magento.test.entity.Cache;
import com.magento.test.entity.CacheTag;
import com.magento.test.entity.CaptchaLog;
import com.magento.test.entity.CatalogCategoryEntity;
import com.magento.test.entity.CatalogCategoryEntityDatetime;
import com.magento.test.entity.CatalogCategoryEntityDecimal;
import com.magento.test.entity.CatalogCategoryEntityInt;
import com.magento.test.entity.CatalogCategoryEntityText;
import com.magento.test.entity.CatalogCategoryEntityVarchar;
import com.magento.test.entity.CatalogCategoryProduct;
import com.magento.test.entity.CatalogCategoryProductIndex;
import com.magento.test.entity.CatalogCategoryProductIndexReplica;
import com.magento.test.entity.CatalogCategoryProductIndexStore1;
import com.magento.test.entity.CatalogCategoryProductIndexStore1Replica;
import com.magento.test.entity.CatalogCategoryProductIndexTmp;
import com.magento.test.entity.CatalogCompareItem;
import com.magento.test.entity.CatalogEavAttribute;
import com.magento.test.entity.CatalogProductBundleOption;
import com.magento.test.entity.CatalogProductBundleOptionValue;
import com.magento.test.entity.CatalogProductBundlePriceIndex;
import com.magento.test.entity.CatalogProductBundleSelection;
import com.magento.test.entity.CatalogProductBundleSelectionPrice;
import com.magento.test.entity.CatalogProductBundleStockIndex;
import com.magento.test.entity.CatalogProductEntity;
import com.magento.test.entity.CatalogProductEntityDatetime;
import com.magento.test.entity.CatalogProductEntityDecimal;
import com.magento.test.entity.CatalogProductEntityGallery;
import com.magento.test.entity.CatalogProductEntityInt;
import com.magento.test.entity.CatalogProductEntityMediaGallery;
import com.magento.test.entity.CatalogProductEntityMediaGalleryValue;
import com.magento.test.entity.CatalogProductEntityMediaGalleryValueToEntity;
import com.magento.test.entity.CatalogProductEntityMediaGalleryValueVideo;
import com.magento.test.entity.CatalogProductEntityText;
import com.magento.test.entity.CatalogProductEntityTierPrice;
import com.magento.test.entity.CatalogProductEntityVarchar;
import com.magento.test.entity.CatalogProductFrontendAction;
import com.magento.test.entity.CatalogProductIndexEav;
import com.magento.test.entity.CatalogProductIndexEavDecimal;
import com.magento.test.entity.CatalogProductIndexEavDecimalIdx;
import com.magento.test.entity.CatalogProductIndexEavDecimalReplica;
import com.magento.test.entity.CatalogProductIndexEavDecimalTmp;
import com.magento.test.entity.CatalogProductIndexEavIdx;
import com.magento.test.entity.CatalogProductIndexEavReplica;
import com.magento.test.entity.CatalogProductIndexEavTmp;
import com.magento.test.entity.CatalogProductIndexPrice;
import com.magento.test.entity.CatalogProductIndexPriceBundleIdx;
import com.magento.test.entity.CatalogProductIndexPriceBundleOptIdx;
import com.magento.test.entity.CatalogProductIndexPriceBundleOptTmp;
import com.magento.test.entity.CatalogProductIndexPriceBundleSelIdx;
import com.magento.test.entity.CatalogProductIndexPriceBundleSelTmp;
import com.magento.test.entity.CatalogProductIndexPriceBundleTmp;
import com.magento.test.entity.CatalogProductIndexPriceCfgOptAgrIdx;
import com.magento.test.entity.CatalogProductIndexPriceCfgOptAgrTmp;
import com.magento.test.entity.CatalogProductIndexPriceCfgOptIdx;
import com.magento.test.entity.CatalogProductIndexPriceCfgOptTmp;
import com.magento.test.entity.CatalogProductIndexPriceDownlodIdx;
import com.magento.test.entity.CatalogProductIndexPriceDownlodTmp;
import com.magento.test.entity.CatalogProductIndexPriceFinalIdx;
import com.magento.test.entity.CatalogProductIndexPriceFinalTmp;
import com.magento.test.entity.CatalogProductIndexPriceIdx;
import com.magento.test.entity.CatalogProductIndexPriceOptAgrIdx;
import com.magento.test.entity.CatalogProductIndexPriceOptAgrTmp;
import com.magento.test.entity.CatalogProductIndexPriceOptIdx;
import com.magento.test.entity.CatalogProductIndexPriceOptTmp;
import com.magento.test.entity.CatalogProductIndexPriceReplica;
import com.magento.test.entity.CatalogProductIndexPriceTmp;
import com.magento.test.entity.CatalogProductIndexTierPrice;
import com.magento.test.entity.CatalogProductIndexWebsite;
import com.magento.test.entity.CatalogProductLink;
import com.magento.test.entity.CatalogProductLinkAttribute;
import com.magento.test.entity.CatalogProductLinkAttributeDecimal;
import com.magento.test.entity.CatalogProductLinkAttributeInt;
import com.magento.test.entity.CatalogProductLinkAttributeVarchar;
import com.magento.test.entity.CatalogProductLinkType;
import com.magento.test.entity.CatalogProductOption;
import com.magento.test.entity.CatalogProductOptionPrice;
import com.magento.test.entity.CatalogProductOptionTitle;
import com.magento.test.entity.CatalogProductOptionTypePrice;
import com.magento.test.entity.CatalogProductOptionTypeTitle;
import com.magento.test.entity.CatalogProductOptionTypeValue;
import com.magento.test.entity.CatalogProductRelation;
import com.magento.test.entity.CatalogProductSuperAttribute;
import com.magento.test.entity.CatalogProductSuperAttributeLabel;
import com.magento.test.entity.CatalogProductSuperLink;
import com.magento.test.entity.CatalogProductWebsite;
import com.magento.test.entity.CatalogUrlRewriteProductCategory;
import com.magento.test.entity.CataloginventoryStock;
import com.magento.test.entity.CataloginventoryStockItem;
import com.magento.test.entity.CataloginventoryStockStatus;
import com.magento.test.entity.CataloginventoryStockStatusIdx;
import com.magento.test.entity.CataloginventoryStockStatusReplica;
import com.magento.test.entity.CataloginventoryStockStatusTmp;
import com.magento.test.entity.Catalogrule;
import com.magento.test.entity.CatalogruleCustomerGroup;
import com.magento.test.entity.CatalogruleGroupWebsite;
import com.magento.test.entity.CatalogruleGroupWebsiteReplica;
import com.magento.test.entity.CatalogruleProduct;
import com.magento.test.entity.CatalogruleProductPrice;
import com.magento.test.entity.CatalogruleProductPriceReplica;
import com.magento.test.entity.CatalogruleProductReplica;
import com.magento.test.entity.CatalogruleWebsite;
import com.magento.test.entity.CatalogsearchFulltextScope1;
import com.magento.test.entity.CatalogsearchRecommendations;
import com.magento.test.entity.CheckoutAgreement;
import com.magento.test.entity.CheckoutAgreementStore;
import com.magento.test.entity.CmsBlock;
import com.magento.test.entity.CmsBlockStore;
import com.magento.test.entity.CmsPage;
import com.magento.test.entity.CmsPageStore;
import com.magento.test.entity.CoreConfigData;
import com.magento.test.entity.CronSchedule;
import com.magento.test.entity.CustomerAddressEntity;
import com.magento.test.entity.CustomerAddressEntityDatetime;
import com.magento.test.entity.CustomerAddressEntityDecimal;
import com.magento.test.entity.CustomerAddressEntityInt;
import com.magento.test.entity.CustomerAddressEntityText;
import com.magento.test.entity.CustomerAddressEntityVarchar;
import com.magento.test.entity.CustomerEavAttribute;
import com.magento.test.entity.CustomerEavAttributeWebsite;
import com.magento.test.entity.CustomerEntity;
import com.magento.test.entity.CustomerEntityDatetime;
import com.magento.test.entity.CustomerEntityDecimal;
import com.magento.test.entity.CustomerEntityInt;
import com.magento.test.entity.CustomerEntityText;
import com.magento.test.entity.CustomerEntityVarchar;
import com.magento.test.entity.CustomerFormAttribute;
import com.magento.test.entity.CustomerGridFlat;
import com.magento.test.entity.CustomerGroup;
import com.magento.test.entity.CustomerLog;
import com.magento.test.entity.CustomerVisitor;
import com.magento.test.entity.DesignChange;
import com.magento.test.entity.DesignConfigGridFlat;
import com.magento.test.entity.DirectoryCountry;
import com.magento.test.entity.DirectoryCountryFormat;
import com.magento.test.entity.DirectoryCountryRegion;
import com.magento.test.entity.DirectoryCountryRegionName;
import com.magento.test.entity.DirectoryCurrencyRate;
import com.magento.test.entity.DownloadableLink;
import com.magento.test.entity.DownloadableLinkPrice;
import com.magento.test.entity.DownloadableLinkPurchased;
import com.magento.test.entity.DownloadableLinkPurchasedItem;
import com.magento.test.entity.DownloadableLinkTitle;
import com.magento.test.entity.DownloadableSample;
import com.magento.test.entity.DownloadableSampleTitle;
import com.magento.test.entity.EavAttribute;
import com.magento.test.entity.EavAttributeGroup;
import com.magento.test.entity.EavAttributeLabel;
import com.magento.test.entity.EavAttributeOption;
import com.magento.test.entity.EavAttributeOptionSwatch;
import com.magento.test.entity.EavAttributeOptionValue;
import com.magento.test.entity.EavAttributeSet;
import com.magento.test.entity.EavEntity;
import com.magento.test.entity.EavEntityAttribute;
import com.magento.test.entity.EavEntityDatetime;
import com.magento.test.entity.EavEntityDecimal;
import com.magento.test.entity.EavEntityInt;
import com.magento.test.entity.EavEntityStore;
import com.magento.test.entity.EavEntityText;
import com.magento.test.entity.EavEntityType;
import com.magento.test.entity.EavEntityVarchar;
import com.magento.test.entity.EavFormElement;
import com.magento.test.entity.EavFormFieldset;
import com.magento.test.entity.EavFormFieldsetLabel;
import com.magento.test.entity.EavFormType;
import com.magento.test.entity.EavFormTypeEntity;
import com.magento.test.entity.EmailAbandonedCart;
import com.magento.test.entity.EmailAutomation;
import com.magento.test.entity.EmailCampaign;
import com.magento.test.entity.EmailCatalog;
import com.magento.test.entity.EmailContact;
import com.magento.test.entity.EmailContactConsent;
import com.magento.test.entity.EmailFailedAuth;
import com.magento.test.entity.EmailImporter;
import com.magento.test.entity.EmailOrder;
import com.magento.test.entity.EmailReview;
import com.magento.test.entity.EmailRules;
import com.magento.test.entity.EmailTemplate;
import com.magento.test.entity.EmailWishlist;
import com.magento.test.entity.Flag;
import com.magento.test.entity.GiftMessage;
import com.magento.test.entity.GoogleoptimizerCode;
import com.magento.test.entity.ImportHistory;
import com.magento.test.entity.ImportexportImportdata;
import com.magento.test.entity.IndexerState;
import com.magento.test.entity.Integration;
import com.magento.test.entity.InventoryGeoname;
import com.magento.test.entity.InventoryLowStockNotificationConfiguration;
import com.magento.test.entity.InventoryReservation;
import com.magento.test.entity.InventoryShipmentSource;
import com.magento.test.entity.InventorySource;
import com.magento.test.entity.InventorySourceCarrierLink;
import com.magento.test.entity.InventorySourceItem;
import com.magento.test.entity.InventorySourceStockLink;
import com.magento.test.entity.InventoryStock;
import com.magento.test.entity.InventoryStockSalesChannel;
import com.magento.test.entity.KlarnaCoreOrder;
import com.magento.test.entity.KlarnaPaymentsQuote;
import com.magento.test.entity.LayoutLink;
import com.magento.test.entity.LayoutUpdate;
import com.magento.test.entity.MagentoAcknowledgedBulk;
import com.magento.test.entity.MagentoBulk;
import com.magento.test.entity.MagentoOperation;
import com.magento.test.entity.MspTfaCountryCodes;
import com.magento.test.entity.MspTfaTrusted;
import com.magento.test.entity.MspTfaUserConfig;
import com.magento.test.entity.MviewState;
import com.magento.test.entity.NewsletterProblem;
import com.magento.test.entity.NewsletterQueue;
import com.magento.test.entity.NewsletterQueueLink;
import com.magento.test.entity.NewsletterQueueStoreLink;
import com.magento.test.entity.NewsletterSubscriber;
import com.magento.test.entity.NewsletterTemplate;
import com.magento.test.entity.OauthConsumer;
import com.magento.test.entity.OauthNonce;
import com.magento.test.entity.OauthToken;
import com.magento.test.entity.OauthTokenRequestLog;
import com.magento.test.entity.PasswordResetRequestEvent;
import com.magento.test.entity.PatchList;
import com.magento.test.entity.PaypalBillingAgreement;
import com.magento.test.entity.PaypalBillingAgreementOrder;
import com.magento.test.entity.PaypalCert;
import com.magento.test.entity.PaypalPaymentTransaction;
import com.magento.test.entity.PaypalSettlementReport;
import com.magento.test.entity.PaypalSettlementReportRow;
import com.magento.test.entity.PersistentSession;
import com.magento.test.entity.ProductAlertPrice;
import com.magento.test.entity.ProductAlertStock;
import com.magento.test.entity.Queue;
import com.magento.test.entity.QueueLock;
import com.magento.test.entity.QueueMessage;
import com.magento.test.entity.QueueMessageStatus;
import com.magento.test.entity.QueuePoisonPill;
import com.magento.test.entity.Quote;
import com.magento.test.entity.QuoteAddress;
import com.magento.test.entity.QuoteAddressItem;
import com.magento.test.entity.QuoteIdMask;
import com.magento.test.entity.QuoteItem;
import com.magento.test.entity.QuoteItemOption;
import com.magento.test.entity.QuotePayment;
import com.magento.test.entity.QuoteShippingRate;
import com.magento.test.entity.Rating;
import com.magento.test.entity.RatingEntity;
import com.magento.test.entity.RatingOption;
import com.magento.test.entity.RatingOptionVote;
import com.magento.test.entity.RatingOptionVoteAggregated;
import com.magento.test.entity.RatingStore;
import com.magento.test.entity.RatingTitle;
import com.magento.test.entity.ReleaseNotificationViewerLog;
import com.magento.test.entity.ReportComparedProductIndex;
import com.magento.test.entity.ReportEvent;
import com.magento.test.entity.ReportEventTypes;
import com.magento.test.entity.ReportViewedProductAggregatedDaily;
import com.magento.test.entity.ReportViewedProductAggregatedMonthly;
import com.magento.test.entity.ReportViewedProductAggregatedYearly;
import com.magento.test.entity.ReportViewedProductIndex;
import com.magento.test.entity.ReportingCounts;
import com.magento.test.entity.ReportingModuleStatus;
import com.magento.test.entity.ReportingOrders;
import com.magento.test.entity.ReportingSystemUpdates;
import com.magento.test.entity.ReportingUsers;
import com.magento.test.entity.Review;
import com.magento.test.entity.ReviewDetail;
import com.magento.test.entity.ReviewEntity;
import com.magento.test.entity.ReviewEntitySummary;
import com.magento.test.entity.ReviewStatus;
import com.magento.test.entity.ReviewStore;
import com.magento.test.entity.SalesBestsellersAggregatedDaily;
import com.magento.test.entity.SalesBestsellersAggregatedMonthly;
import com.magento.test.entity.SalesBestsellersAggregatedYearly;
import com.magento.test.entity.SalesCreditmemo;
import com.magento.test.entity.SalesCreditmemoComment;
import com.magento.test.entity.SalesCreditmemoGrid;
import com.magento.test.entity.SalesCreditmemoItem;
import com.magento.test.entity.SalesInvoice;
import com.magento.test.entity.SalesInvoiceComment;
import com.magento.test.entity.SalesInvoiceGrid;
import com.magento.test.entity.SalesInvoiceItem;
import com.magento.test.entity.SalesInvoicedAggregated;
import com.magento.test.entity.SalesInvoicedAggregatedOrder;
import com.magento.test.entity.SalesOrder;
import com.magento.test.entity.SalesOrderAddress;
import com.magento.test.entity.SalesOrderAggregatedCreated;
import com.magento.test.entity.SalesOrderAggregatedUpdated;
import com.magento.test.entity.SalesOrderGrid;
import com.magento.test.entity.SalesOrderItem;
import com.magento.test.entity.SalesOrderPayment;
import com.magento.test.entity.SalesOrderStatus;
import com.magento.test.entity.SalesOrderStatusHistory;
import com.magento.test.entity.SalesOrderStatusLabel;
import com.magento.test.entity.SalesOrderStatusState;
import com.magento.test.entity.SalesOrderTax;
import com.magento.test.entity.SalesOrderTaxItem;
import com.magento.test.entity.SalesPaymentTransaction;
import com.magento.test.entity.SalesRefundedAggregated;
import com.magento.test.entity.SalesRefundedAggregatedOrder;
import com.magento.test.entity.SalesSequenceMeta;
import com.magento.test.entity.SalesSequenceProfile;
import com.magento.test.entity.SalesShipment;
import com.magento.test.entity.SalesShipmentComment;
import com.magento.test.entity.SalesShipmentGrid;
import com.magento.test.entity.SalesShipmentItem;
import com.magento.test.entity.SalesShipmentTrack;
import com.magento.test.entity.SalesShippingAggregated;
import com.magento.test.entity.SalesShippingAggregatedOrder;
import com.magento.test.entity.Salesrule;
import com.magento.test.entity.SalesruleCoupon;
import com.magento.test.entity.SalesruleCouponAggregated;
import com.magento.test.entity.SalesruleCouponAggregatedOrder;
import com.magento.test.entity.SalesruleCouponAggregatedUpdated;
import com.magento.test.entity.SalesruleCouponUsage;
import com.magento.test.entity.SalesruleCustomer;
import com.magento.test.entity.SalesruleCustomerGroup;
import com.magento.test.entity.SalesruleLabel;
import com.magento.test.entity.SalesruleProductAttribute;
import com.magento.test.entity.SalesruleWebsite;
import com.magento.test.entity.SearchQuery;
import com.magento.test.entity.SearchSynonyms;
import com.magento.test.entity.SendfriendLog;
import com.magento.test.entity.SequenceCreditmemo0;
import com.magento.test.entity.SequenceCreditmemo1;
import com.magento.test.entity.SequenceInvoice0;
import com.magento.test.entity.SequenceInvoice1;
import com.magento.test.entity.SequenceOrder0;
import com.magento.test.entity.SequenceOrder1;
import com.magento.test.entity.SequenceShipment0;
import com.magento.test.entity.SequenceShipment1;
import com.magento.test.entity.Session;
import com.magento.test.entity.SetupModule;
import com.magento.test.entity.ShippingTablerate;
import com.magento.test.entity.SignifydCase;
import com.magento.test.entity.Sitemap;
import com.magento.test.entity.Store;
import com.magento.test.entity.StoreGroup;
import com.magento.test.entity.StoreWebsite;
import com.magento.test.entity.TaxCalculation;
import com.magento.test.entity.TaxCalculationRate;
import com.magento.test.entity.TaxCalculationRateTitle;
import com.magento.test.entity.TaxCalculationRule;
import com.magento.test.entity.TaxClass;
import com.magento.test.entity.TaxOrderAggregatedCreated;
import com.magento.test.entity.TaxOrderAggregatedUpdated;
import com.magento.test.entity.TemandoCheckoutAddress;
import com.magento.test.entity.TemandoCollectionPointSearch;
import com.magento.test.entity.TemandoOrder;
import com.magento.test.entity.TemandoOrderCollectionPoint;
import com.magento.test.entity.TemandoOrderPickupLocation;
import com.magento.test.entity.TemandoPickupLocationSearch;
import com.magento.test.entity.TemandoQuoteCollectionPoint;
import com.magento.test.entity.TemandoQuotePickupLocation;
import com.magento.test.entity.TemandoShipment;
import com.magento.test.entity.Theme;
import com.magento.test.entity.ThemeFile;
import com.magento.test.entity.Translation;
import com.magento.test.entity.UiBookmark;
import com.magento.test.entity.UrlRewrite;
import com.magento.test.entity.Variable;
import com.magento.test.entity.VariableValue;
import com.magento.test.entity.VaultPaymentToken;
import com.magento.test.entity.VaultPaymentTokenOrderPaymentLink;
import com.magento.test.entity.VertexCustomerCode;
import com.magento.test.entity.VertexInvoiceSent;
import com.magento.test.entity.VertexOrderInvoiceStatus;
import com.magento.test.entity.VertexSalesCreditmemoItemInvoiceTextCode;
import com.magento.test.entity.VertexSalesCreditmemoItemTaxCode;
import com.magento.test.entity.VertexSalesCreditmemoItemVertexTaxCode;
import com.magento.test.entity.VertexSalesOrderItemInvoiceTextCode;
import com.magento.test.entity.VertexSalesOrderItemTaxCode;
import com.magento.test.entity.VertexSalesOrderItemVertexTaxCode;
import com.magento.test.entity.VertexTaxrequest;
import com.magento.test.entity.WeeeTax;
import com.magento.test.entity.Widget;
import com.magento.test.entity.WidgetInstance;
import com.magento.test.entity.WidgetInstancePage;
import com.magento.test.entity.WidgetInstancePageLayout;
import com.magento.test.entity.Wishlist;
import com.magento.test.entity.WishlistItem;
import com.magento.test.entity.WishlistItemOption;
import com.magento.test.entity.DataLoadingStatus;
import com.magento.test.entity.Loadingstatus;

@Stateless
@Named("DefaultDataLoadingDao")
public class DefaultDataLoadingDao implements DataLoadingDao {

  private static final Logger logger = Logger.getLogger(DefaultDataLoadingDao.class.getName());
  private JpaDao dao;

  @Inject
  @Named("DefaultJpaDao")
  public DefaultDataLoadingDao(JpaDao dao) {
    this.dao = dao;
  }

  /** {@inheritDoc} */
  @Override
  public DataLoadingStatus update(DataLoadingStatus e) {
    return dao.update(e);
  }

  /** {@inheritDoc} */
  @Override
  public DataLoadingStatus getLoadingStatus(String type) {
    DataLoadingStatus loadingStatus = dao.find(DataLoadingStatus.class, type);
    if (null == loadingStatus) {
      loadingStatus = new DataLoadingStatus(type, Loadingstatus.NEW);
      dao.create(loadingStatus);
    }
    return loadingStatus;
  }

  /** {@inheritDoc} */
  @Override
  public <E> E create(E e) {
    return dao.create(e);
  }

  /** {@inheritDoc} */
  @Override
  public void delete(String id) {
    dao.delete(DataLoadingStatus.class, id);
  }

  /** {@inheritDoc} */
  @Override
  public void deleteAll() {
    dao.deleteAll(AdminPasswords.class);
    dao.deleteAll(AdminSystemMessages.class);
    dao.deleteAll(AdminUser.class);
    dao.deleteAll(AdminUserSession.class);
    dao.deleteAll(AdminnotificationInbox.class);
    dao.deleteAll(AmazonCustomer.class);
    dao.deleteAll(AmazonPendingAuthorization.class);
    dao.deleteAll(AmazonPendingCapture.class);
    dao.deleteAll(AmazonPendingRefund.class);
    dao.deleteAll(AmazonQuote.class);
    dao.deleteAll(AmazonSalesOrder.class);
    dao.deleteAll(AuthorizationRole.class);
    dao.deleteAll(AuthorizationRule.class);
    dao.deleteAll(Cache.class);
    dao.deleteAll(CacheTag.class);
    dao.deleteAll(CaptchaLog.class);
    dao.deleteAll(CatalogCategoryEntity.class);
    dao.deleteAll(CatalogCategoryEntityDatetime.class);
    dao.deleteAll(CatalogCategoryEntityDecimal.class);
    dao.deleteAll(CatalogCategoryEntityInt.class);
    dao.deleteAll(CatalogCategoryEntityText.class);
    dao.deleteAll(CatalogCategoryEntityVarchar.class);
    dao.deleteAll(CatalogCategoryProduct.class);
    dao.deleteAll(CatalogCategoryProductIndex.class);
    dao.deleteAll(CatalogCategoryProductIndexReplica.class);
    dao.deleteAll(CatalogCategoryProductIndexStore1.class);
    dao.deleteAll(CatalogCategoryProductIndexStore1Replica.class);
    dao.deleteAll(CatalogCategoryProductIndexTmp.class);
    dao.deleteAll(CatalogCompareItem.class);
    dao.deleteAll(CatalogEavAttribute.class);
    dao.deleteAll(CatalogProductBundleOption.class);
    dao.deleteAll(CatalogProductBundleOptionValue.class);
    dao.deleteAll(CatalogProductBundlePriceIndex.class);
    dao.deleteAll(CatalogProductBundleSelection.class);
    dao.deleteAll(CatalogProductBundleSelectionPrice.class);
    dao.deleteAll(CatalogProductBundleStockIndex.class);
    dao.deleteAll(CatalogProductEntity.class);
    dao.deleteAll(CatalogProductEntityDatetime.class);
    dao.deleteAll(CatalogProductEntityDecimal.class);
    dao.deleteAll(CatalogProductEntityGallery.class);
    dao.deleteAll(CatalogProductEntityInt.class);
    dao.deleteAll(CatalogProductEntityMediaGallery.class);
    dao.deleteAll(CatalogProductEntityMediaGalleryValue.class);
    dao.deleteAll(CatalogProductEntityMediaGalleryValueToEntity.class);
    dao.deleteAll(CatalogProductEntityMediaGalleryValueVideo.class);
    dao.deleteAll(CatalogProductEntityText.class);
    dao.deleteAll(CatalogProductEntityTierPrice.class);
    dao.deleteAll(CatalogProductEntityVarchar.class);
    dao.deleteAll(CatalogProductFrontendAction.class);
    dao.deleteAll(CatalogProductIndexEav.class);
    dao.deleteAll(CatalogProductIndexEavDecimal.class);
    dao.deleteAll(CatalogProductIndexEavDecimalIdx.class);
    dao.deleteAll(CatalogProductIndexEavDecimalReplica.class);
    dao.deleteAll(CatalogProductIndexEavDecimalTmp.class);
    dao.deleteAll(CatalogProductIndexEavIdx.class);
    dao.deleteAll(CatalogProductIndexEavReplica.class);
    dao.deleteAll(CatalogProductIndexEavTmp.class);
    dao.deleteAll(CatalogProductIndexPrice.class);
    dao.deleteAll(CatalogProductIndexPriceBundleIdx.class);
    dao.deleteAll(CatalogProductIndexPriceBundleOptIdx.class);
    dao.deleteAll(CatalogProductIndexPriceBundleOptTmp.class);
    dao.deleteAll(CatalogProductIndexPriceBundleSelIdx.class);
    dao.deleteAll(CatalogProductIndexPriceBundleSelTmp.class);
    dao.deleteAll(CatalogProductIndexPriceBundleTmp.class);
    dao.deleteAll(CatalogProductIndexPriceCfgOptAgrIdx.class);
    dao.deleteAll(CatalogProductIndexPriceCfgOptAgrTmp.class);
    dao.deleteAll(CatalogProductIndexPriceCfgOptIdx.class);
    dao.deleteAll(CatalogProductIndexPriceCfgOptTmp.class);
    dao.deleteAll(CatalogProductIndexPriceDownlodIdx.class);
    dao.deleteAll(CatalogProductIndexPriceDownlodTmp.class);
    dao.deleteAll(CatalogProductIndexPriceFinalIdx.class);
    dao.deleteAll(CatalogProductIndexPriceFinalTmp.class);
    dao.deleteAll(CatalogProductIndexPriceIdx.class);
    dao.deleteAll(CatalogProductIndexPriceOptAgrIdx.class);
    dao.deleteAll(CatalogProductIndexPriceOptAgrTmp.class);
    dao.deleteAll(CatalogProductIndexPriceOptIdx.class);
    dao.deleteAll(CatalogProductIndexPriceOptTmp.class);
    dao.deleteAll(CatalogProductIndexPriceReplica.class);
    dao.deleteAll(CatalogProductIndexPriceTmp.class);
    dao.deleteAll(CatalogProductIndexTierPrice.class);
    dao.deleteAll(CatalogProductIndexWebsite.class);
    dao.deleteAll(CatalogProductLink.class);
    dao.deleteAll(CatalogProductLinkAttribute.class);
    dao.deleteAll(CatalogProductLinkAttributeDecimal.class);
    dao.deleteAll(CatalogProductLinkAttributeInt.class);
    dao.deleteAll(CatalogProductLinkAttributeVarchar.class);
    dao.deleteAll(CatalogProductLinkType.class);
    dao.deleteAll(CatalogProductOption.class);
    dao.deleteAll(CatalogProductOptionPrice.class);
    dao.deleteAll(CatalogProductOptionTitle.class);
    dao.deleteAll(CatalogProductOptionTypePrice.class);
    dao.deleteAll(CatalogProductOptionTypeTitle.class);
    dao.deleteAll(CatalogProductOptionTypeValue.class);
    dao.deleteAll(CatalogProductRelation.class);
    dao.deleteAll(CatalogProductSuperAttribute.class);
    dao.deleteAll(CatalogProductSuperAttributeLabel.class);
    dao.deleteAll(CatalogProductSuperLink.class);
    dao.deleteAll(CatalogProductWebsite.class);
    dao.deleteAll(CatalogUrlRewriteProductCategory.class);
    dao.deleteAll(CataloginventoryStock.class);
    dao.deleteAll(CataloginventoryStockItem.class);
    dao.deleteAll(CataloginventoryStockStatus.class);
    dao.deleteAll(CataloginventoryStockStatusIdx.class);
    dao.deleteAll(CataloginventoryStockStatusReplica.class);
    dao.deleteAll(CataloginventoryStockStatusTmp.class);
    dao.deleteAll(Catalogrule.class);
    dao.deleteAll(CatalogruleCustomerGroup.class);
    dao.deleteAll(CatalogruleGroupWebsite.class);
    dao.deleteAll(CatalogruleGroupWebsiteReplica.class);
    dao.deleteAll(CatalogruleProduct.class);
    dao.deleteAll(CatalogruleProductPrice.class);
    dao.deleteAll(CatalogruleProductPriceReplica.class);
    dao.deleteAll(CatalogruleProductReplica.class);
    dao.deleteAll(CatalogruleWebsite.class);
    dao.deleteAll(CatalogsearchFulltextScope1.class);
    dao.deleteAll(CatalogsearchRecommendations.class);
    dao.deleteAll(CheckoutAgreement.class);
    dao.deleteAll(CheckoutAgreementStore.class);
    dao.deleteAll(CmsBlock.class);
    dao.deleteAll(CmsBlockStore.class);
    dao.deleteAll(CmsPage.class);
    dao.deleteAll(CmsPageStore.class);
    dao.deleteAll(CoreConfigData.class);
    dao.deleteAll(CronSchedule.class);
    dao.deleteAll(CustomerAddressEntity.class);
    dao.deleteAll(CustomerAddressEntityDatetime.class);
    dao.deleteAll(CustomerAddressEntityDecimal.class);
    dao.deleteAll(CustomerAddressEntityInt.class);
    dao.deleteAll(CustomerAddressEntityText.class);
    dao.deleteAll(CustomerAddressEntityVarchar.class);
    dao.deleteAll(CustomerEavAttribute.class);
    dao.deleteAll(CustomerEavAttributeWebsite.class);
    dao.deleteAll(CustomerEntity.class);
    dao.deleteAll(CustomerEntityDatetime.class);
    dao.deleteAll(CustomerEntityDecimal.class);
    dao.deleteAll(CustomerEntityInt.class);
    dao.deleteAll(CustomerEntityText.class);
    dao.deleteAll(CustomerEntityVarchar.class);
    dao.deleteAll(CustomerFormAttribute.class);
    dao.deleteAll(CustomerGridFlat.class);
    dao.deleteAll(CustomerGroup.class);
    dao.deleteAll(CustomerLog.class);
    dao.deleteAll(CustomerVisitor.class);
    dao.deleteAll(DesignChange.class);
    dao.deleteAll(DesignConfigGridFlat.class);
    dao.deleteAll(DirectoryCountry.class);
    dao.deleteAll(DirectoryCountryFormat.class);
    dao.deleteAll(DirectoryCountryRegion.class);
    dao.deleteAll(DirectoryCountryRegionName.class);
    dao.deleteAll(DirectoryCurrencyRate.class);
    dao.deleteAll(DownloadableLink.class);
    dao.deleteAll(DownloadableLinkPrice.class);
    dao.deleteAll(DownloadableLinkPurchased.class);
    dao.deleteAll(DownloadableLinkPurchasedItem.class);
    dao.deleteAll(DownloadableLinkTitle.class);
    dao.deleteAll(DownloadableSample.class);
    dao.deleteAll(DownloadableSampleTitle.class);
    dao.deleteAll(EavAttribute.class);
    dao.deleteAll(EavAttributeGroup.class);
    dao.deleteAll(EavAttributeLabel.class);
    dao.deleteAll(EavAttributeOption.class);
    dao.deleteAll(EavAttributeOptionSwatch.class);
    dao.deleteAll(EavAttributeOptionValue.class);
    dao.deleteAll(EavAttributeSet.class);
    dao.deleteAll(EavEntity.class);
    dao.deleteAll(EavEntityAttribute.class);
    dao.deleteAll(EavEntityDatetime.class);
    dao.deleteAll(EavEntityDecimal.class);
    dao.deleteAll(EavEntityInt.class);
    dao.deleteAll(EavEntityStore.class);
    dao.deleteAll(EavEntityText.class);
    dao.deleteAll(EavEntityType.class);
    dao.deleteAll(EavEntityVarchar.class);
    dao.deleteAll(EavFormElement.class);
    dao.deleteAll(EavFormFieldset.class);
    dao.deleteAll(EavFormFieldsetLabel.class);
    dao.deleteAll(EavFormType.class);
    dao.deleteAll(EavFormTypeEntity.class);
    dao.deleteAll(EmailAbandonedCart.class);
    dao.deleteAll(EmailAutomation.class);
    dao.deleteAll(EmailCampaign.class);
    dao.deleteAll(EmailCatalog.class);
    dao.deleteAll(EmailContact.class);
    dao.deleteAll(EmailContactConsent.class);
    dao.deleteAll(EmailFailedAuth.class);
    dao.deleteAll(EmailImporter.class);
    dao.deleteAll(EmailOrder.class);
    dao.deleteAll(EmailReview.class);
    dao.deleteAll(EmailRules.class);
    dao.deleteAll(EmailTemplate.class);
    dao.deleteAll(EmailWishlist.class);
    dao.deleteAll(Flag.class);
    dao.deleteAll(GiftMessage.class);
    dao.deleteAll(GoogleoptimizerCode.class);
    dao.deleteAll(ImportHistory.class);
    dao.deleteAll(ImportexportImportdata.class);
    dao.deleteAll(IndexerState.class);
    dao.deleteAll(Integration.class);
    dao.deleteAll(InventoryGeoname.class);
    dao.deleteAll(InventoryLowStockNotificationConfiguration.class);
    dao.deleteAll(InventoryReservation.class);
    dao.deleteAll(InventoryShipmentSource.class);
    dao.deleteAll(InventorySource.class);
    dao.deleteAll(InventorySourceCarrierLink.class);
    dao.deleteAll(InventorySourceItem.class);
    dao.deleteAll(InventorySourceStockLink.class);
    dao.deleteAll(InventoryStock.class);
    dao.deleteAll(InventoryStockSalesChannel.class);
    dao.deleteAll(KlarnaCoreOrder.class);
    dao.deleteAll(KlarnaPaymentsQuote.class);
    dao.deleteAll(LayoutLink.class);
    dao.deleteAll(LayoutUpdate.class);
    dao.deleteAll(MagentoAcknowledgedBulk.class);
    dao.deleteAll(MagentoBulk.class);
    dao.deleteAll(MagentoOperation.class);
    dao.deleteAll(MspTfaCountryCodes.class);
    dao.deleteAll(MspTfaTrusted.class);
    dao.deleteAll(MspTfaUserConfig.class);
    dao.deleteAll(MviewState.class);
    dao.deleteAll(NewsletterProblem.class);
    dao.deleteAll(NewsletterQueue.class);
    dao.deleteAll(NewsletterQueueLink.class);
    dao.deleteAll(NewsletterQueueStoreLink.class);
    dao.deleteAll(NewsletterSubscriber.class);
    dao.deleteAll(NewsletterTemplate.class);
    dao.deleteAll(OauthConsumer.class);
    dao.deleteAll(OauthNonce.class);
    dao.deleteAll(OauthToken.class);
    dao.deleteAll(OauthTokenRequestLog.class);
    dao.deleteAll(PasswordResetRequestEvent.class);
    dao.deleteAll(PatchList.class);
    dao.deleteAll(PaypalBillingAgreement.class);
    dao.deleteAll(PaypalBillingAgreementOrder.class);
    dao.deleteAll(PaypalCert.class);
    dao.deleteAll(PaypalPaymentTransaction.class);
    dao.deleteAll(PaypalSettlementReport.class);
    dao.deleteAll(PaypalSettlementReportRow.class);
    dao.deleteAll(PersistentSession.class);
    dao.deleteAll(ProductAlertPrice.class);
    dao.deleteAll(ProductAlertStock.class);
    dao.deleteAll(Queue.class);
    dao.deleteAll(QueueLock.class);
    dao.deleteAll(QueueMessage.class);
    dao.deleteAll(QueueMessageStatus.class);
    dao.deleteAll(QueuePoisonPill.class);
    dao.deleteAll(Quote.class);
    dao.deleteAll(QuoteAddress.class);
    dao.deleteAll(QuoteAddressItem.class);
    dao.deleteAll(QuoteIdMask.class);
    dao.deleteAll(QuoteItem.class);
    dao.deleteAll(QuoteItemOption.class);
    dao.deleteAll(QuotePayment.class);
    dao.deleteAll(QuoteShippingRate.class);
    dao.deleteAll(Rating.class);
    dao.deleteAll(RatingEntity.class);
    dao.deleteAll(RatingOption.class);
    dao.deleteAll(RatingOptionVote.class);
    dao.deleteAll(RatingOptionVoteAggregated.class);
    dao.deleteAll(RatingStore.class);
    dao.deleteAll(RatingTitle.class);
    dao.deleteAll(ReleaseNotificationViewerLog.class);
    dao.deleteAll(ReportComparedProductIndex.class);
    dao.deleteAll(ReportEvent.class);
    dao.deleteAll(ReportEventTypes.class);
    dao.deleteAll(ReportViewedProductAggregatedDaily.class);
    dao.deleteAll(ReportViewedProductAggregatedMonthly.class);
    dao.deleteAll(ReportViewedProductAggregatedYearly.class);
    dao.deleteAll(ReportViewedProductIndex.class);
    dao.deleteAll(ReportingCounts.class);
    dao.deleteAll(ReportingModuleStatus.class);
    dao.deleteAll(ReportingOrders.class);
    dao.deleteAll(ReportingSystemUpdates.class);
    dao.deleteAll(ReportingUsers.class);
    dao.deleteAll(Review.class);
    dao.deleteAll(ReviewDetail.class);
    dao.deleteAll(ReviewEntity.class);
    dao.deleteAll(ReviewEntitySummary.class);
    dao.deleteAll(ReviewStatus.class);
    dao.deleteAll(ReviewStore.class);
    dao.deleteAll(SalesBestsellersAggregatedDaily.class);
    dao.deleteAll(SalesBestsellersAggregatedMonthly.class);
    dao.deleteAll(SalesBestsellersAggregatedYearly.class);
    dao.deleteAll(SalesCreditmemo.class);
    dao.deleteAll(SalesCreditmemoComment.class);
    dao.deleteAll(SalesCreditmemoGrid.class);
    dao.deleteAll(SalesCreditmemoItem.class);
    dao.deleteAll(SalesInvoice.class);
    dao.deleteAll(SalesInvoiceComment.class);
    dao.deleteAll(SalesInvoiceGrid.class);
    dao.deleteAll(SalesInvoiceItem.class);
    dao.deleteAll(SalesInvoicedAggregated.class);
    dao.deleteAll(SalesInvoicedAggregatedOrder.class);
    dao.deleteAll(SalesOrder.class);
    dao.deleteAll(SalesOrderAddress.class);
    dao.deleteAll(SalesOrderAggregatedCreated.class);
    dao.deleteAll(SalesOrderAggregatedUpdated.class);
    dao.deleteAll(SalesOrderGrid.class);
    dao.deleteAll(SalesOrderItem.class);
    dao.deleteAll(SalesOrderPayment.class);
    dao.deleteAll(SalesOrderStatus.class);
    dao.deleteAll(SalesOrderStatusHistory.class);
    dao.deleteAll(SalesOrderStatusLabel.class);
    dao.deleteAll(SalesOrderStatusState.class);
    dao.deleteAll(SalesOrderTax.class);
    dao.deleteAll(SalesOrderTaxItem.class);
    dao.deleteAll(SalesPaymentTransaction.class);
    dao.deleteAll(SalesRefundedAggregated.class);
    dao.deleteAll(SalesRefundedAggregatedOrder.class);
    dao.deleteAll(SalesSequenceMeta.class);
    dao.deleteAll(SalesSequenceProfile.class);
    dao.deleteAll(SalesShipment.class);
    dao.deleteAll(SalesShipmentComment.class);
    dao.deleteAll(SalesShipmentGrid.class);
    dao.deleteAll(SalesShipmentItem.class);
    dao.deleteAll(SalesShipmentTrack.class);
    dao.deleteAll(SalesShippingAggregated.class);
    dao.deleteAll(SalesShippingAggregatedOrder.class);
    dao.deleteAll(Salesrule.class);
    dao.deleteAll(SalesruleCoupon.class);
    dao.deleteAll(SalesruleCouponAggregated.class);
    dao.deleteAll(SalesruleCouponAggregatedOrder.class);
    dao.deleteAll(SalesruleCouponAggregatedUpdated.class);
    dao.deleteAll(SalesruleCouponUsage.class);
    dao.deleteAll(SalesruleCustomer.class);
    dao.deleteAll(SalesruleCustomerGroup.class);
    dao.deleteAll(SalesruleLabel.class);
    dao.deleteAll(SalesruleProductAttribute.class);
    dao.deleteAll(SalesruleWebsite.class);
    dao.deleteAll(SearchQuery.class);
    dao.deleteAll(SearchSynonyms.class);
    dao.deleteAll(SendfriendLog.class);
    dao.deleteAll(SequenceCreditmemo0.class);
    dao.deleteAll(SequenceCreditmemo1.class);
    dao.deleteAll(SequenceInvoice0.class);
    dao.deleteAll(SequenceInvoice1.class);
    dao.deleteAll(SequenceOrder0.class);
    dao.deleteAll(SequenceOrder1.class);
    dao.deleteAll(SequenceShipment0.class);
    dao.deleteAll(SequenceShipment1.class);
    dao.deleteAll(Session.class);
    dao.deleteAll(SetupModule.class);
    dao.deleteAll(ShippingTablerate.class);
    dao.deleteAll(SignifydCase.class);
    dao.deleteAll(Sitemap.class);
    dao.deleteAll(Store.class);
    dao.deleteAll(StoreGroup.class);
    dao.deleteAll(StoreWebsite.class);
    dao.deleteAll(TaxCalculation.class);
    dao.deleteAll(TaxCalculationRate.class);
    dao.deleteAll(TaxCalculationRateTitle.class);
    dao.deleteAll(TaxCalculationRule.class);
    dao.deleteAll(TaxClass.class);
    dao.deleteAll(TaxOrderAggregatedCreated.class);
    dao.deleteAll(TaxOrderAggregatedUpdated.class);
    dao.deleteAll(TemandoCheckoutAddress.class);
    dao.deleteAll(TemandoCollectionPointSearch.class);
    dao.deleteAll(TemandoOrder.class);
    dao.deleteAll(TemandoOrderCollectionPoint.class);
    dao.deleteAll(TemandoOrderPickupLocation.class);
    dao.deleteAll(TemandoPickupLocationSearch.class);
    dao.deleteAll(TemandoQuoteCollectionPoint.class);
    dao.deleteAll(TemandoQuotePickupLocation.class);
    dao.deleteAll(TemandoShipment.class);
    dao.deleteAll(Theme.class);
    dao.deleteAll(ThemeFile.class);
    dao.deleteAll(Translation.class);
    dao.deleteAll(UiBookmark.class);
    dao.deleteAll(UrlRewrite.class);
    dao.deleteAll(Variable.class);
    dao.deleteAll(VariableValue.class);
    dao.deleteAll(VaultPaymentToken.class);
    dao.deleteAll(VaultPaymentTokenOrderPaymentLink.class);
    dao.deleteAll(VertexCustomerCode.class);
    dao.deleteAll(VertexInvoiceSent.class);
    dao.deleteAll(VertexOrderInvoiceStatus.class);
    dao.deleteAll(VertexSalesCreditmemoItemInvoiceTextCode.class);
    dao.deleteAll(VertexSalesCreditmemoItemTaxCode.class);
    dao.deleteAll(VertexSalesCreditmemoItemVertexTaxCode.class);
    dao.deleteAll(VertexSalesOrderItemInvoiceTextCode.class);
    dao.deleteAll(VertexSalesOrderItemTaxCode.class);
    dao.deleteAll(VertexSalesOrderItemVertexTaxCode.class);
    dao.deleteAll(VertexTaxrequest.class);
    dao.deleteAll(WeeeTax.class);
    dao.deleteAll(Widget.class);
    dao.deleteAll(WidgetInstance.class);
    dao.deleteAll(WidgetInstancePage.class);
    dao.deleteAll(WidgetInstancePageLayout.class);
    dao.deleteAll(Wishlist.class);
    dao.deleteAll(WishlistItem.class);
    dao.deleteAll(WishlistItemOption.class);
  }
}
