/**
 * %% Copyright (C) 2021 DataScience 9 LLC %% Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a
 * copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License. #L%
 *
 * <p>This code is 100% AUTO generated. Please do not modify it DIRECTLY If you need new features or
 * function or changes please update the templates then submit the template through our web
 * interface.
 */
package com.magento.test.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.Table;
import java.io.Serializable;
import javax.persistence.Basic;

@Entity
@IdClass(UrlRewriteId.class)
@Table(name = "url_rewrite")
public class UrlRewrite implements Serializable {
  private static final long serialVersionUID = 163445090711266912L;

  /** Description: store_id. */
  @javax.validation.constraints.NotNull
  @javax.persistence.Id
  @Column(name = "store_id")
  private java.lang.Integer storeId;
  /** Description: url_rewrite_id. */
  @javax.validation.constraints.NotNull
  @javax.persistence.Id
  @Column(name = "url_rewrite_id")
  private java.lang.Integer urlRewriteId;
  /** Description: request_path. */
  @javax.validation.constraints.NotNull
  @javax.persistence.Id
  @Column(name = "request_path")
  private java.lang.String requestPath;

  /** Description: entity_type. */
  @javax.validation.constraints.NotNull
  @Basic
  @Column(name = "entity_type", length = 32)
  private java.lang.String entityType;
  /** Description: entity_id. */
  @javax.validation.constraints.NotNull
  @Basic
  @Column(name = "entity_id")
  private java.lang.Integer entityId;
  /** Description: target_path. */
  @Basic
  @Column(name = "target_path", length = 255)
  private java.lang.String targetPath;
  /** Description: redirect_type. */
  @javax.validation.constraints.NotNull
  @Basic
  @Column(name = "redirect_type")
  private java.lang.Integer redirectType;
  /** Description: description. */
  @Basic
  @Column(name = "description", length = 255)
  private java.lang.String description;
  /** Description: is_autogenerated. */
  @javax.validation.constraints.NotNull
  @Basic
  @Column(name = "is_autogenerated")
  private java.lang.Integer isAutogenerated;
  /** Description: metadata. */
  @Basic
  @Column(name = "metadata", length = 255)
  private java.lang.String metadata;

  public UrlRewrite() {}

  public java.lang.Integer getStoreId() {
    return this.storeId;
  }

  public java.lang.Integer getUrlRewriteId() {
    return this.urlRewriteId;
  }

  public java.lang.String getRequestPath() {
    return this.requestPath;
  }

  public void setStoreId(java.lang.Integer storeId) {
    this.storeId = storeId;
  }

  public void setUrlRewriteId(java.lang.Integer urlRewriteId) {
    this.urlRewriteId = urlRewriteId;
  }

  public void setRequestPath(java.lang.String requestPath) {
    this.requestPath = requestPath;
  }

  public java.lang.String getEntityType() {
    return this.entityType;
  }

  public java.lang.Integer getEntityId() {
    return this.entityId;
  }

  public java.lang.String getTargetPath() {
    return this.targetPath;
  }

  public java.lang.Integer getRedirectType() {
    return this.redirectType;
  }

  public java.lang.String getDescription() {
    return this.description;
  }

  public java.lang.Integer getIsAutogenerated() {
    return this.isAutogenerated;
  }

  public java.lang.String getMetadata() {
    return this.metadata;
  }

  public void setEntityType(java.lang.String entityType) {
    this.entityType = entityType;
  }

  public void setEntityId(java.lang.Integer entityId) {
    this.entityId = entityId;
  }

  public void setTargetPath(java.lang.String targetPath) {
    this.targetPath = targetPath;
  }

  public void setRedirectType(java.lang.Integer redirectType) {
    this.redirectType = redirectType;
  }

  public void setDescription(java.lang.String description) {
    this.description = description;
  }

  public void setIsAutogenerated(java.lang.Integer isAutogenerated) {
    this.isAutogenerated = isAutogenerated;
  }

  public void setMetadata(java.lang.String metadata) {
    this.metadata = metadata;
  }
}
